services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html:rw
    expose:
      - "9000"
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: nette
      POSTGRES_USER: nette
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - php

volumes:
  dbdata:
